/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    impacts: Impact;
    payments: Payment;
    'career-applications': CareerApplication;
    'contact-submissions': ContactSubmission;
    'newsletter-subscribers': NewsletterSubscriber;
    'team-carousel-images': TeamCarouselImage;
    'leadership-team': LeadershipTeam;
    'advisory-board': AdvisoryBoard;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    impacts: ImpactsSelect<false> | ImpactsSelect<true>;
    payments: PaymentsSelect<false> | PaymentsSelect<true>;
    'career-applications': CareerApplicationsSelect<false> | CareerApplicationsSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    'newsletter-subscribers': NewsletterSubscribersSelect<false> | NewsletterSubscribersSelect<true>;
    'team-carousel-images': TeamCarouselImagesSelect<false> | TeamCarouselImagesSelect<true>;
    'leadership-team': LeadershipTeamSelect<false> | LeadershipTeamSelect<true>;
    'advisory-board': AdvisoryBoardSelect<false> | AdvisoryBoardSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    'email-settings': EmailSetting;
    'social-settings': SocialSetting;
    'footer-links': FooterLink;
  };
  globalsSelect: {
    'email-settings': EmailSettingsSelect<false> | EmailSettingsSelect<true>;
    'social-settings': SocialSettingsSelect<false> | SocialSettingsSelect<true>;
    'footer-links': FooterLinksSelect<false> | FooterLinksSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "impacts".
 */
export interface Impact {
  id: number;
  /**
   * Internal title for this impact statistic
   */
  title: string;
  /**
   * The main impact number (e.g., 4.31, 177000, 160)
   */
  val: number;
  /**
   * Unit or modifier for the primary value (e.g., "million *", "*")
   */
  suffix?: string | null;
  /**
   * Number of decimal places to display for the primary value (e.g., 0, 1, 2)
   */
  decimals?: number | null;
  /**
   * Main description of the impact (e.g., "Impact sessions in total")
   */
  desc: string;
  /**
   * Light Lives specific number (e.g., 145000, 11000, 27)
   */
  val2: number;
  /**
   * Light Lives specific description (e.g., "delivered by Light Lives")
   */
  desc2: string;
  /**
   * Number of decimal places to display for the secondary value
   */
  decimals2?: number | null;
  /**
   * Order in which this impact should be displayed (lower numbers first)
   */
  displayOrder?: number | null;
  /**
   * Whether this impact should use a pointer animation
   */
  usePointer?: boolean | null;
  /**
   * Whether this impact should be displayed on the website
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments".
 */
export interface Payment {
  id: number;
  razorpayOrderId: string;
  razorpayPaymentId?: string | null;
  razorpaySignature?: string | null;
  /**
   * Amount in INR (minimum ₹1, maximum ₹10,00,000)
   */
  amount: number;
  currency: 'INR' | 'USD';
  paymentType: 'onetime' | 'recurring' | 'upi';
  paymentStatus: 'pending' | 'completed' | 'failed' | 'cancelled';
  firstName?: string | null;
  lastName: string;
  email: string;
  phone: string;
  /**
   * Complete address for 80G certificate generation
   */
  address?: string | null;
  /**
   * Required for 80G tax exemption certificate (Format: ABCDE1234F)
   */
  panNumber?: string | null;
  isRecurring?: boolean | null;
  monthlyContributionAgreed?: boolean | null;
  privacyPolicyAgreed: boolean;
  /**
   * Auto-generated receipt number
   */
  receiptNumber?: string | null;
  /**
   * IP address of the donor
   */
  ipAddress?: string | null;
  /**
   * Browser user agent string
   */
  userAgent?: string | null;
  /**
   * 80G tax exemption certificate issued
   */
  certificateIssued?: boolean | null;
  certificateNumber?: string | null;
  certificateIssuedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "career-applications".
 */
export interface CareerApplication {
  id: number;
  /**
   * Full name of the applicant
   */
  name: string;
  /**
   * Email address for communication
   */
  email: string;
  /**
   * Mobile number with country code
   */
  mobile: string;
  /**
   * Resume/CV file (PDF, DOC, DOCX)
   */
  resume: number | Media;
  /**
   * Current status of the application
   */
  applicationStatus: 'new' | 'reviewing' | 'interview' | 'accepted' | 'rejected';
  /**
   * Internal notes about the applicant
   */
  notes?: string | null;
  /**
   * IP address when application was submitted
   */
  ipAddress?: string | null;
  /**
   * Browser user agent string
   */
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  /**
   * First name of the person contacting us
   */
  firstName: string;
  /**
   * Last name of the person contacting us
   */
  lastName: string;
  /**
   * Full name (auto-generated)
   */
  name?: string | null;
  /**
   * Email address for communication
   */
  email: string;
  /**
   * Phone number (optional)
   */
  phone?: string | null;
  /**
   * Subject of the inquiry
   */
  subject: 'sponsorship' | 'partnership' | 'volunteer' | 'programs' | 'csr' | 'other';
  /**
   * Message content
   */
  message: string;
  /**
   * Current status of the inquiry
   */
  status: 'new' | 'in-progress' | 'responded' | 'closed';
  /**
   * Priority level of the inquiry
   */
  priority: 'low' | 'normal' | 'high' | 'urgent';
  /**
   * Team member assigned to handle this inquiry
   */
  assignedTo?: (number | null) | User;
  /**
   * Internal notes about the inquiry
   */
  notes?: string | null;
  /**
   * IP address when submission was made
   */
  ipAddress?: string | null;
  /**
   * Browser user agent string
   */
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers".
 */
export interface NewsletterSubscriber {
  id: number;
  /**
   * Email address of the subscriber
   */
  email: string;
  /**
   * Subscription status
   */
  status: 'active' | 'unsubscribed';
  /**
   * Date when the user subscribed
   */
  subscribedAt?: string | null;
  /**
   * Date when the user unsubscribed
   */
  unsubscribedAt?: string | null;
  /**
   * IP address when subscription was made
   */
  ipAddress?: string | null;
  /**
   * Browser user agent string
   */
  userAgent?: string | null;
  /**
   * Source of the subscription
   */
  source?: ('footer' | 'contact' | 'popup' | 'manual') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-carousel-images".
 */
export interface TeamCarouselImage {
  id: number;
  image: number | Media;
  /**
   * Describe the image for accessibility
   */
  alt: string;
  /**
   * Lower numbers appear first in the carousel
   */
  displayOrder: number;
  /**
   * Uncheck to hide this image from the carousel
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leadership-team".
 */
export interface LeadershipTeam {
  id: number;
  name: string;
  /**
   * e.g., Chief Executive Officer, Director of Operations
   */
  jobRole: string;
  /**
   * Square image recommended (1:1 aspect ratio)
   */
  profileImage: number | Media;
  /**
   * Lower numbers appear first in the grid
   */
  displayOrder: number;
  /**
   * Uncheck to hide this member from the team page
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "advisory-board".
 */
export interface AdvisoryBoard {
  id: number;
  name: string;
  /**
   * Square image recommended (1:1 aspect ratio)
   */
  profileImage: number | Media;
  /**
   * Full paragraph about the advisory board member
   */
  bio: string;
  /**
   * Lower numbers appear first on the page
   */
  displayOrder: number;
  /**
   * Uncheck to hide this member from the team page
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'impacts';
        value: number | Impact;
      } | null)
    | ({
        relationTo: 'payments';
        value: number | Payment;
      } | null)
    | ({
        relationTo: 'career-applications';
        value: number | CareerApplication;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null)
    | ({
        relationTo: 'newsletter-subscribers';
        value: number | NewsletterSubscriber;
      } | null)
    | ({
        relationTo: 'team-carousel-images';
        value: number | TeamCarouselImage;
      } | null)
    | ({
        relationTo: 'leadership-team';
        value: number | LeadershipTeam;
      } | null)
    | ({
        relationTo: 'advisory-board';
        value: number | AdvisoryBoard;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "impacts_select".
 */
export interface ImpactsSelect<T extends boolean = true> {
  title?: T;
  val?: T;
  suffix?: T;
  decimals?: T;
  desc?: T;
  val2?: T;
  desc2?: T;
  decimals2?: T;
  displayOrder?: T;
  usePointer?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments_select".
 */
export interface PaymentsSelect<T extends boolean = true> {
  razorpayOrderId?: T;
  razorpayPaymentId?: T;
  razorpaySignature?: T;
  amount?: T;
  currency?: T;
  paymentType?: T;
  paymentStatus?: T;
  firstName?: T;
  lastName?: T;
  email?: T;
  phone?: T;
  address?: T;
  panNumber?: T;
  isRecurring?: T;
  monthlyContributionAgreed?: T;
  privacyPolicyAgreed?: T;
  receiptNumber?: T;
  ipAddress?: T;
  userAgent?: T;
  certificateIssued?: T;
  certificateNumber?: T;
  certificateIssuedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "career-applications_select".
 */
export interface CareerApplicationsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  mobile?: T;
  resume?: T;
  applicationStatus?: T;
  notes?: T;
  ipAddress?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  name?: T;
  email?: T;
  phone?: T;
  subject?: T;
  message?: T;
  status?: T;
  priority?: T;
  assignedTo?: T;
  notes?: T;
  ipAddress?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers_select".
 */
export interface NewsletterSubscribersSelect<T extends boolean = true> {
  email?: T;
  status?: T;
  subscribedAt?: T;
  unsubscribedAt?: T;
  ipAddress?: T;
  userAgent?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-carousel-images_select".
 */
export interface TeamCarouselImagesSelect<T extends boolean = true> {
  image?: T;
  alt?: T;
  displayOrder?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leadership-team_select".
 */
export interface LeadershipTeamSelect<T extends boolean = true> {
  name?: T;
  jobRole?: T;
  profileImage?: T;
  displayOrder?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "advisory-board_select".
 */
export interface AdvisoryBoardSelect<T extends boolean = true> {
  name?: T;
  profileImage?: T;
  bio?: T;
  displayOrder?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Manage email configurations for automated notifications
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-settings".
 */
export interface EmailSetting {
  id: number;
  /**
   * Configure emails sent when users submit the contact form
   */
  contactEmails: {
    /**
     * Turn on/off email notifications for contact form submissions
     */
    enabled?: boolean | null;
    /**
     * Primary email address to receive contact form notifications
     */
    adminEmail: string;
    /**
     * Additional email addresses to CC on contact form notifications
     */
    ccEmails?:
      | {
          email: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Send automatic confirmation email to users who submit the contact form
     */
    autoReplyEnabled?: boolean | null;
    /**
     * Subject line for the auto-reply email
     */
    autoReplySubject?: string | null;
    /**
     * How long users can expect to wait for a response
     */
    responseTime?: string | null;
    /**
     * Additional message to include in the auto-reply email
     */
    customMessage?: string | null;
  };
  /**
   * Configure emails sent when users submit job applications
   */
  careerEmails: {
    /**
     * Turn on/off email notifications for career applications
     */
    enabled?: boolean | null;
    /**
     * Primary email address to receive career application notifications
     */
    hrEmail: string;
    /**
     * Additional email addresses to CC on career application notifications
     */
    ccEmails?:
      | {
          email: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Send automatic confirmation email to job applicants
     */
    applicantAutoReply?: boolean | null;
    /**
     * Subject line for the applicant confirmation email
     */
    applicantSubject?: string | null;
    /**
     * How long applicants can expect to wait for a response
     */
    reviewTime?: string | null;
    /**
     * Additional message to include in the applicant confirmation email
     */
    customApplicantMessage?: string | null;
  };
  /**
   * General organization information used in email templates
   */
  organization: {
    /**
     * Full name of the organization
     */
    name: string;
    /**
     * Physical address of the organization
     */
    address?: string | null;
    /**
     * Primary phone number for the organization
     */
    phone?: string | null;
    /**
     * Default email address for replies
     */
    replyToEmail?: string | null;
    /**
     * Main website URL
     */
    websiteUrl?: string | null;
  };
  /**
   * Customize the appearance and branding of email templates
   */
  styling?: {
    /**
     * Primary brand color (hex code)
     */
    primaryColor?: string | null;
    /**
     * Secondary brand color (hex code)
     */
    secondaryColor?: string | null;
    /**
     * URL to organization logo for email headers (optional)
     */
    logoUrl?: string | null;
    /**
     * Custom text to display in email footers
     */
    footerText?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage social media links and contact information displayed in the footer
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-settings".
 */
export interface SocialSetting {
  id: number;
  /**
   * Primary contact details displayed in the footer
   */
  contact?: {
    /**
     * Primary contact phone number
     */
    phone?: string | null;
    /**
     * Primary contact email address
     */
    email?: string | null;
    /**
     * Organization physical address
     */
    address?: string | null;
  };
  /**
   * Social media profile URLs
   */
  socialMedia?: {
    /**
     * Full URL to Facebook page
     */
    facebook?: string | null;
    /**
     * Full URL to Twitter/X profile
     */
    twitter?: string | null;
    /**
     * Full URL to Instagram profile
     */
    instagram?: string | null;
    /**
     * Full URL to LinkedIn page
     */
    linkedin?: string | null;
    /**
     * Full URL to YouTube channel
     */
    youtube?: string | null;
  };
  /**
   * Additional content displayed in the footer
   */
  footer?: {
    /**
     * Brief description of the organization displayed in the footer
     */
    description?: string | null;
    /**
     * Official NGO registration number
     */
    registrationNumber?: string | null;
    /**
     * Copyright year (defaults to current year)
     */
    copyrightYear?: number | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage footer navigation links organized by categories
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer-links".
 */
export interface FooterLink {
  id: number;
  /**
   * Links for the "Quick Links" section in the footer
   */
  quickLinks?:
    | {
        /**
         * Display text for the link
         */
        label: string;
        /**
         * Choose whether this links to a page, document, or external URL
         */
        linkType: 'page' | 'document' | 'external';
        /**
         * Internal page path (e.g., /about/mission)
         */
        pagePath?: string | null;
        /**
         * Upload a PDF or document file
         */
        document?: (number | null) | Media;
        /**
         * Full external URL (e.g., https://example.com)
         */
        externalUrl?: string | null;
        /**
         * Open link in a new tab (recommended for external links and documents)
         */
        openInNewTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Links for the "Legal" section in the footer (certificates, compliance docs)
   */
  legalLinks?:
    | {
        /**
         * Display text for the link
         */
        label: string;
        /**
         * Choose whether this links to a page, document, or external URL
         */
        linkType: 'page' | 'document' | 'external';
        /**
         * Internal page path
         */
        pagePath?: string | null;
        /**
         * Upload a PDF or document file (recommended for certificates)
         */
        document?: (number | null) | Media;
        /**
         * Full external URL
         */
        externalUrl?: string | null;
        /**
         * Open link in a new tab (recommended for documents)
         */
        openInNewTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Links for the "Get Involved" section in the footer
   */
  getInvolvedLinks?:
    | {
        /**
         * Display text for the link
         */
        label: string;
        /**
         * Choose whether this links to a page, document, or external URL
         */
        linkType: 'page' | 'document' | 'external';
        /**
         * Internal page path (e.g., /sponsor)
         */
        pagePath?: string | null;
        /**
         * Upload a PDF or document file
         */
        document?: (number | null) | Media;
        /**
         * Full external URL (e.g., https://donate.example.com)
         */
        externalUrl?: string | null;
        /**
         * Open link in a new tab (recommended for external links)
         */
        openInNewTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional additional links for the "Stay Connected" section (social media and newsletter are handled separately)
   */
  stayConnectedLinks?:
    | {
        /**
         * Display text for the link
         */
        label: string;
        /**
         * Choose whether this links to a page, document, or external URL
         */
        linkType: 'page' | 'document' | 'external';
        /**
         * Internal page path
         */
        pagePath?: string | null;
        /**
         * Upload a PDF or document file
         */
        document?: (number | null) | Media;
        /**
         * Full external URL
         */
        externalUrl?: string | null;
        /**
         * Open link in a new tab
         */
        openInNewTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Links displayed in the bottom copyright bar (e.g., Privacy Policy, Terms)
   */
  policyLinks?:
    | {
        /**
         * Display text for the link
         */
        label: string;
        /**
         * Choose whether this links to a page, document, or external URL
         */
        linkType: 'page' | 'document' | 'external';
        /**
         * Internal page path (e.g., /privacy)
         */
        pagePath?: string | null;
        /**
         * Upload a PDF or document file
         */
        document?: (number | null) | Media;
        /**
         * Full external URL
         */
        externalUrl?: string | null;
        /**
         * Open link in a new tab
         */
        openInNewTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-settings_select".
 */
export interface EmailSettingsSelect<T extends boolean = true> {
  contactEmails?:
    | T
    | {
        enabled?: T;
        adminEmail?: T;
        ccEmails?:
          | T
          | {
              email?: T;
              id?: T;
            };
        autoReplyEnabled?: T;
        autoReplySubject?: T;
        responseTime?: T;
        customMessage?: T;
      };
  careerEmails?:
    | T
    | {
        enabled?: T;
        hrEmail?: T;
        ccEmails?:
          | T
          | {
              email?: T;
              id?: T;
            };
        applicantAutoReply?: T;
        applicantSubject?: T;
        reviewTime?: T;
        customApplicantMessage?: T;
      };
  organization?:
    | T
    | {
        name?: T;
        address?: T;
        phone?: T;
        replyToEmail?: T;
        websiteUrl?: T;
      };
  styling?:
    | T
    | {
        primaryColor?: T;
        secondaryColor?: T;
        logoUrl?: T;
        footerText?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-settings_select".
 */
export interface SocialSettingsSelect<T extends boolean = true> {
  contact?:
    | T
    | {
        phone?: T;
        email?: T;
        address?: T;
      };
  socialMedia?:
    | T
    | {
        facebook?: T;
        twitter?: T;
        instagram?: T;
        linkedin?: T;
        youtube?: T;
      };
  footer?:
    | T
    | {
        description?: T;
        registrationNumber?: T;
        copyrightYear?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer-links_select".
 */
export interface FooterLinksSelect<T extends boolean = true> {
  quickLinks?:
    | T
    | {
        label?: T;
        linkType?: T;
        pagePath?: T;
        document?: T;
        externalUrl?: T;
        openInNewTab?: T;
        id?: T;
      };
  legalLinks?:
    | T
    | {
        label?: T;
        linkType?: T;
        pagePath?: T;
        document?: T;
        externalUrl?: T;
        openInNewTab?: T;
        id?: T;
      };
  getInvolvedLinks?:
    | T
    | {
        label?: T;
        linkType?: T;
        pagePath?: T;
        document?: T;
        externalUrl?: T;
        openInNewTab?: T;
        id?: T;
      };
  stayConnectedLinks?:
    | T
    | {
        label?: T;
        linkType?: T;
        pagePath?: T;
        document?: T;
        externalUrl?: T;
        openInNewTab?: T;
        id?: T;
      };
  policyLinks?:
    | T
    | {
        label?: T;
        linkType?: T;
        pagePath?: T;
        document?: T;
        externalUrl?: T;
        openInNewTab?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}