name: Sync main and tags to fork

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  sync-fork:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history and tags

      - name: Push main branch to fork
        env:
          FORK_PAT: ${{ secrets.FORK_PAT }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote add fork https://x-access-token:${FORK_PAT}@github.com/<fork-owner>/<fork-repo>.git
          git push fork main --force
          git push fork --tags
